server.port=8210

spring.datasource.url=jdbc:informix-sqli://srvmac02test:1544/synergia:informixserver=synergia_test;CLIENT_LOCALE=en_us.utf8;DB_LOCALE=en_US.8859-1;IFX_USE_STRENC=true;
spring.datasource.username=batchsyn
spring.datasource.password=pepe
spring.datasource.driver-class-name=com.informix.jdbc.IfxDriver
spring.datasource.autoCommit=false
spring.datasource.hikari.read-only=true

server.undertow.accesslog.enabled=true
server.undertow.accesslog.dir=../logs
