spring.application.name=iMacSrv

spring.config.import=file:./@project.artifactId@.properties

logging.config=./@project.artifactId@-logback.xml

server.undertow.accesslog.enabled=true
server.undertow.accesslog.prefix=access_@project.artifactId@.
